name: Code standards and docker build

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-python:
    name: Lint Code using pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install .[dev]

      - name: Lint using pre-commit
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          hatch run lint >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker build
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          docker build . >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
