name: Code standards and docker build

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-python:
    name: Lint Code using pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install .[dev]

      - name: Lint using pre-commit
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          hatch run type >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Type checking
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          hatch run lint >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  test-postgres16:
    name: Test code using pytest-cov
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: turplanlegger
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install .[dev]

      - name: Test with pytest
        env:
          TP_DATABASE_URI: postgresql://postgres:postgres@localhost/turplanlegger?connect_timeout=10&application_name=turplanlegger-unittest
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          hatch run test-cov >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY


  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker build
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          docker build . >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
